apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
data:
  vault-config: |
    storage "etcd" {
      address = "http://etcd-database:2379"
      etcd_api = "v3"
      path = "/vault/"
    }
    
    listener "tcp" {
      address     = "0.0.0.0:8200"
      tls_disable = 1
      disable_mlock = true
    }
    disable_mlock = true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-deployment
  labels:
    app: vault
spec:
  replicas: 3
  selector:
    matchLabels:
        app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - name: vault
        image: quay.io/casek14/vault:11.1.3
        ports:
        - name: tcp
          containerPort: 8200
        - name: telemetry
          containerPort: 8125
        volumeMounts:
        - name: config-volume
          mountPath: /vault/config/local.hcl
          subPath: vault-config
      volumes:
        - name: config-volume
          configMap:
            name: vault-config
---
apiVersion: v1
kind: Service
metadata:
  name: vault-service
spec:
  selector:
    app: vault
  ports:
  - name: vault
    protocol: TCP
    port: 8200
  - name: telemetry
    protocol: TCP
    port: 8125
