---
apiVersion: v1
kind: Service
metadata:
  name: ambassador
  namespace: ambassador
spec:
  selector:
    service: ambassador
  ports:
    - name: http
      port: 80
      targetPort: 8080 
  externalIPs:
    - 192.168.0.102
