apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
data:
  vault-config: |
    storage "etcd" {
      address = "http://etcd-database:2379"
      etcd_api = "v3"
      path = "/vault/"
    }
    
    listener "tcp" {
      address     = "0.0.0.0:8200"
      tls_disable = 1
    }
    
    telemetry {
      statsite_address = "0.0.0.0:8125"
      disable_hostname = true
      ui = true
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-deployment
  labels:
    app: vault
spec:
  replicas: 3
  selector:
    matchLabels:
        app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - name: vault
        image: vault:1.1.3
        ports:
        - name: tcp
          containerPort: 8200
        - name: telemetry
          containerPort: 8125
        volumeMounts:
        - name: config-volume
          mountPath: /vault/config/local.json
      volumes:
        - name: config-volume
          configMap:
            name: vault-config
